apiVersion: v1
kind: Service
metadata:
  name: iris-model-service
spec:
  selector:
    app: iris-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
